version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./batch.sql:/docker-entrypoint-initdb.d/batch.sql
      - csv_volume:/usr/share/app
    ports:
      - '5432:5432'
  web-app:
    image: aldeebob/qa-api-service
    depends_on:
      - db
    ports:
      - '5000:5000'
volumes:
  csv_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/csv
networks:
  default:
    external:
        name: sdc